### ISSUE TITLE
Create Simulation for Robot by Utilizing WPILib's built-in Robot Simulation Tool

### ISSUE THREAD

**Issue by OneLemonyBoi** [systemoverloadrobotics/Robot2022#2]
Information: https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/robot-simulation/drivesim-tutorial/diffdrive-sim-overview.html

Swerve Example: https://www.chiefdelphi.com/t/simulating-a-swerve-drive-with-the-2021-wpilib-libraries/393534

**Comment by Basil070104** [comment]
It's already integrated with the software you downloaded. If you click on the three dots on the top right corner, you can click on the simulated robot code.

**Comment by OneLemonyBoi** [comment]
Yes, but it requires some code to integrate the robot with the system.

**Comment by Basil070104** [comment]
Oh, that's what you're talking about. We can definitely do that.

**Comment by OneLemonyBoi** [comment]
Not Possible :(
